### ISSUE TITLE
How change timepicker selected time fill color?

### ISSUE THREAD

**Issue by diosney** [T00rk/bootstrap-material-datetimepicker#156]
As title says, I'm trying to integrate the component into my theme and need to change programmatically the green fill color in the timepicker to match my theme main color, which it seems to be hardcoded in the js (#8BC34A).

That could be an input option since all the other colors can be changed by means of CSS, but this particular case can't since it is embeded in the SVG markup.

Thanks!

**Comment by diosney** [comment]
If you add a class to the selected hour, f.i., this can do something like:

```css
svg .selected-hour, svg .selected-minute {
    fill: blue !important;
}
```

but currently no such class is added.

**Comment by diosney** [comment]
Well, already solved the issue, with:

```css
.svg-clock [fill='#8BC34A'] {
    fill: red;
}
```
I will close the issue but could be useful if classes at least are added to sv paths that are selected, that will make this future-proof since you may change the color at an time.
