### ISSUE TITLE
problem with top border radius

### ISSUE THREAD

**Issue by FezVrasta** [T00rk/bootstrap-material-datetimepicker#2]
`.dtp-header` should have a 2px border radius on the top corners.

```` css
.dtp-header {
  border-radius: 2px 2px 0 0;
}
````
